<?php

$questions_and_answers = array(
	'What is your ideal vacation?' => array(
		'Odyssey'	=> 'Disney World with the family.',
		'Accord'	=> 'Shopping in NYC\'s trendiest boutiques.',
		'Pilot'		=> 'Bungee jumping off the Kawarau Bridge in New Zealand.',
		'CR-V'		=> 'Las Vegas with your best friends.',
		'Insight'	=> 'Hiking through the Smokey Mountains.',
		'Civic'		=> 'Watching your favorite team in the Super Bowl.'),
	'When it\'s time to eat, you go for?' => array(
		'Accord'	=> 'A dry martini with a spinach salad.',
		'Odyssey'	=> 'A home cooked meal of steak and potatoes hits the spot.',
		'Pilot'		=> 'The latest ethnic joint, no matter how weird.',
		'Insight'	=> 'My patented tofu and sprouts sandwich.',
		'CR-V'		=> 'Whatever is for lunch at Starbucks.',
		'Civic'		=> 'A hot dog while watching the game.'),	
	'Your friends are most likely to describe you as?' => array(
		'Insight'	=> 'Kind to living creatures.',
		'Accord'	=> 'Stylish.',
		'Pilot'		=> 'Living on the Edge.',
		'CR-V'		=> 'Playful.',
		'Odyssey'	=> 'Domesticated.',
		'Civic'		=> 'A Social Butterfly.'),
	'Which of these is closest to your dream job?' => array(
		'Accord'	=> 'Being paid 100K to show up in a suit.',
		'Insight'	=> 'Dolphin training at Sea World.',
		'CR-V'		=> 'Landing a gig as a racecar driver.',
		'Civic'		=> 'Spinning tunes in European nightclubs.',
		'Pilot'		=> 'Performing as a stunt double.',
		'Odyssey'	=> 'Getting paid to travel the world.'),
	'You Never Miss an Episode of?' => array(
		'Odyssey'	=> 'Dancing With The Stars.',
		'CR-V'		=> 'The Amazing Race',
		'Civic'		=> 'The Real World.',
		'Accord'	=> 'Sex and the City.',
		'Pilot'		=> 'Survivor.',
		'Insight'	=> 'Dirty Jobs.'),
	'During Your Down Time You?' => array(
		'Pilot'		=> 'Go for a run.',
		'Odyssey'	=> 'Take a nap.',
		'Insight'	=> 'Volunteer your time.',
		'CR-V'		=> 'Get your friends together to play a game of touch football.',
		'Civic'		=> 'Play video games and/or search the web.',
		'Accord'	=> 'Meet a friend for coffee.'),
	'What is your typical order at Starbucks?' => array(
		'CR-V'		=> 'Their seasonal beverage.',
		'Civic'		=> 'A hot chocolate.',
		'Odyssey'	=> 'A quick coffee on the go.',
		'Insight'	=> 'A Vanilla Soy Latte.',
		'Accord'	=> 'A Venti, Non-Fat, Sugar Free Caramel Macchiato.',
		'Pilot'		=> 'Two shots of Expresso.'),
	'When you wake up in the morning what is the first thing you think?' => array(
		'Civic'		=> 'Hit the alarm and go back to bed.',
		'CR-V'		=> 'Let\'s get this day started.',
		'Pilot'		=> 'I\'m ready for a 10 mile run.',
		'Odyssey'	=> 'Need coffee stat.',
		'Accord'	=> 'What am I going to wear today?',
		'Insight'	=> 'I hope the weather is nice today.'),
	'Who is your favorite celebrity?' => array(
		'Odyssey'	=> 'Martha Stewart.',
		'Accord'	=> 'Jennifer Aniston.',
		'Pilot'		=> 'Lance Armstrong.',
		'Civic'		=> 'Derek Jeter.',
		'Insight'	=> 'Jeff Corwin.',
		'CR-V'		=> 'Tiger Woods.'),
	'What kind of movie are you most likely to go see on a Friday night?' => array(
		'Civic'		=> 'Anything with Will Ferrell.',
		'CR-V'		=> 'The latest box office hit.',
		'Insight'	=> 'An action packed adventure.',
		'Accord'	=> 'A romantic comedy.',
		'Pilot'		=> 'A documentary.',
		'Odyssey'	=> 'Whatever the kids want to see.')
);

$cars_and_responses = array(
	'Accord'	=> array(
		'response'	=> 'Ingeniously simple yet overflowing with luxury and fabulously fun.  You know style and are not afraid to show it!',
		'know'		=> '<em>Car and Driver</em> names the Accord a 2009 10 Best Car for a record 23rd time.',
		'img'		=> 'http://honda.simplyearl.com/cars/Accord.jpg',
		'tally'		=> 0),
	'Civic'		=> array(
		'response'	=> 'Cute and sporty with an always on the go mentality.  With your youth and a jammed pack schedule you like to take your daily routine to a whole new level!',
		'know'		=> 'Kelley Blue Book puts the Civic on its "2009 Best Resale Value: Top 10" list.',
		'img'		=> 'http://honda.simplyearl.com/cars/Civic.jpg',
		'tally'		=> 0),
	'CR-V'		=> array(
		'response'	=> 'We all crave something and you my friend want it all.  And for a go-getter like yourself you have no problem handling any of life\'s little curveballs!',
		'know'		=> 'Kiplinger.com names the 2008 CR-V "Best in Class."',
		'img'		=> 'http://honda.simplyearl.com/cars/CR-V.jpg',
		'tally'		=> 0),
	'Insight'	=> array(
		'response'	=> 'Fun, fearless and conscious about our environment.  With the adventurous life you lead you are always ready to seize the moment, yet know how to do so responsibly!',
		'know'		=> 'The Honda Insight is the most affordable new hybrid in the U.S.',
		'img'		=> 'http://honda.simplyearl.com/cars/Insight.jpg',
		'tally'		=> 0),
	'Odyssey'	=> array(
		'response'	=> 'You are stylish, yet enjoy the comforts of home and spending time with your family.  Your "go with the flow" mentality helps you get through the day while safely taxiing the children around!',
		'know'		=> 'The insurance Institute for Highway Safety has named <em>Odyssey</em> a 2009 "Top Safety Pick."',
		'img'		=> 'http://honda.simplyearl.com/cars/Odyssey.jpg',
		'tally'		=> 0),
	'Pilot'		=> array(
		'response'	=> 'You are a powerful performer always looking for the perfect moment... the sweet spot.  And when you find that moment you are prepared and equipped and ready for whatever adventure life throws at you!',
		'know'		=> 'The 2009 Pilot has received 5-star frontal and 5-star side impact crash-test ratings from the National Highway Traffic Safety Administration (NHTSA).',
		'img'		=> 'http://honda.simplyearl.com/cars/Pilot.jpg',
		'tally'		=> 0)
);
?>